version: '3'
services:

  db1:
    image: mariadb
    ports:
      - 3317:3306
    volumes:
      # - ./db1/data:/var/lib/mysql
      - ./db1/conf:/etc/mysql/conf.d/
      - ./scripts:/opt/scripts
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD

  db2:
    image: mariadb
    ports:
      - 3318:3306
    volumes:
      # - ./db2/data:/var/lib/mysql
      - ./db2/conf:/etc/mysql/conf.d/
      - ./scripts:/opt/scripts
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
    depends_on:
      - db1

